export const calm = [
  { name: "Archivo", path: "/public/fonts/calm/Archivo.woff2" },
  { name: "DM Sans", path: "/public/fonts/calm/DM_Sans.woff2" },
  { name: "Figtree", path: "/public/fonts/calm/Figtree.woff2" },
  { name: "Funnel Sans", path: "/public/fonts/calm/Funnel_Sans.woff2" },
  { name: "IBM Plex Sans", path: "/public/fonts/calm/IBM_Plex_Sans.woff2" },
  { name: "Inclusive Sans", path: "/public/fonts/calm/Inclusive_Sans.woff2" },
  { name: "Instrument Sans", path: "/public/fonts/calm/Instrument_Sans.woff2" },
  { name: "Inter", path: "/public/fonts/calm/Inter.woff2" },
  { name: "Lato", path: "/public/fonts/calm/Lato.woff2" },
  { name: "Lexend", path: "/public/fonts/calm/Lexend.woff2" },
  { name: "Manrope", path: "/public/fonts/calm/Manrope.woff2" },
  { name: "Montserrat", path: "/public/fonts/calm/Montserrat.woff2" },
  { name: "Noto Sans", path: "/public/fonts/calm/Noto_Sans.woff2" },
  { name: "Nunito", path: "/public/fonts/calm/Nunito.woff2" },
  { name: "Onest", path: "/public/fonts/calm/Onest.woff2" },
  { name: "Poppins", path: "/public/fonts/calm/Poppins.woff2" },
  { name: "PT Sans", path: "/public/fonts/calm/PT_Sans.woff2" },
  { name: "Quicksand", path: "/public/fonts/calm/Quicksand.woff2" },
  { name: "Raleway", path: "/public/fonts/calm/Raleway.woff2" },
  { name: "Red Hat Text", path: "/public/fonts/calm/Red_Hat_Text.woff2" },
  { name: "Rubik", path: "/public/fonts/calm/Rubik.woff2" },
  { name: "Sarala", path: "/public/fonts/calm/Sarala.woff2" },
];
