export const calm = [
  { name: "Archivo", url: "/fonts/calm/Archivo.woff2" },
  { name: "DM Sans", url: "/fonts/calm/DM_Sans.woff2" },
  { name: "Figtree", url: "/fonts/calm/Figtree.woff2" },
  { name: "Funnel Sans", url: "/fonts/calm/Funnel_Sans.woff2" },
  { name: "IBM Plex Sans", url: "/fonts/calm/IBM_Plex_Sans.woff2" },
  { name: "Inclusive Sans", url: "/fonts/calm/Inclusive_Sans.woff2" },
  { name: "Instrument Sans", url: "/fonts/calm/Instrument_Sans.woff2" },
  { name: "Inter", url: "/fonts/calm/Inter.woff2" },
  { name: "Lato", url: "/fonts/calm/Lato.woff2" },
  { name: "Lexend", url: "/fonts/calm/Lexend.woff2" },
  { name: "Manrope", url: "/fonts/calm/Manrope.woff2" },
  { name: "Montserrat", url: "/fonts/calm/Montserrat.woff2" },
  { name: "Noto Sans", url: "/fonts/calm/Noto_Sans.woff2" },
  { name: "Nunito", url: "/fonts/calm/Nunito.woff2" },
  { name: "Onest", url: "/fonts/calm/Onest.woff2" },
  { name: "Poppins", url: "/fonts/calm/Poppins.woff2" },
  { name: "PT Sans", url: "/fonts/calm/PT_Sans.woff2" },
  { name: "Quicksand", url: "/fonts/calm/Quicksand.woff2" },
  { name: "Raleway", url: "/fonts/calm/Raleway.woff2" },
  { name: "Red Hat Text", url: "/fonts/calm/Red_Hat_Text.woff2" },
  { name: "Rubik", url: "/fonts/calm/Rubik.woff2" },
  { name: "Sarala", url: "/fonts/calm/Sarala.woff2" },
];
