export const calm = [
  { name: "Archivo", path: "lib/fonts/calm/Archivo.ttf" },
  { name: "DM Sans", path: "lib/fonts/calm/DM_Sans.ttf" },
  { name: "Figtree", path: "lib/fonts/calm/Figtree.ttf" },
  { name: "Funnel Sans", path: "lib/fonts/calm/Funnel_Sans.ttf" },
  { name: "IBM Plex Sans", path: "lib/fonts/calm/IBM_Plex_Sans.ttf" },
  { name: "Inclusive Sans", path: "lib/fonts/calm/Inclusive_Sans.ttf" },
  { name: "Instrument Sans", path: "lib/fonts/calm/Instrument_Sans.ttf" },
  { name: "Inter", path: "lib/fonts/calm/Inter.ttf" },
  { name: "Lato", path: "lib/fonts/calm/Lato.ttf" },
  { name: "Lexend", path: "lib/fonts/calm/Lexend.ttf" },
  { name: "Manrope", path: "lib/fonts/calm/Manrope.ttf" },
  { name: "Montserrat", path: "lib/fonts/calm/Montserrat.ttf" },
  { name: "Noto Sans", path: "lib/fonts/calm/Noto_Sans.ttf" },
  { name: "Nunito", path: "lib/fonts/calm/Nunito.ttf" },
  { name: "Onest", path: "lib/fonts/calm/Onest.ttf" },
  { name: "Poppins", path: "lib/fonts/calm/Poppins.ttf" },
  { name: "PT Sans", path: "lib/fonts/calm/PT_Sans.ttf" },
  { name: "Quicksand", path: "lib/fonts/calm/Quicksand.ttf" },
  { name: "Raleway", path: "lib/fonts/calm/Raleway.ttf" },
  { name: "Red Hat Text", path: "lib/fonts/calm/Red_Hat_Text.ttf" },
  { name: "Rubik", path: "lib/fonts/calm/Rubik.ttf" },
  { name: "Sarala", path: "lib/fonts/calm/Sarala.ttf" },
];
