export const playful = [
  { name: "Atma", path: "fonts/playful/Atma.woff2" },
  { name: "Chela One", path: "fonts/playful/Chela_One.woff2" },
  { name: "Chewy", path: "fonts/playful/Chewy.woff2" },
  { name: "Chicle", path: "fonts/playful/Chicle.woff2" },
  {
    name: "Covered By Your Grace",
    path: "fonts/playful/Covered_By_Your_Grace.woff2",
  },
  { name: "Crushed", path: "fonts/playful/Crushed.woff2" },
  { name: "DynaPuff", path: "fonts/playful/DynaPuff.woff2" },
  { name: "Gabriela", path: "fonts/playful/Gabriela.woff2" },
  { name: "Galindo", path: "fonts/playful/Galindo.woff2" },
  { name: "Gochi Hand", path: "fonts/playful/Gochi_Hand.woff2" },
  { name: "Jolly Lodger", path: "fonts/playful/Jolly_Lodger.woff2" },
  { name: "Itim", path: "fonts/playful/Itim.woff2" },
  { name: "Mouse Memoirs", path: "fonts/playful/Mouse_Memoirs.woff2" },
  { name: "Patrick Hand", path: "fonts/playful/Patrick_Hand.woff2" },
  { name: "Ranchers", path: "fonts/playful/Ranchers.woff2" },
  { name: "Rum Raisin", path: "fonts/playful/Rum_Raisin.woff2" },
  { name: "Shrikhand", path: "fonts/playful/Shrikhand.woff2" },
  { name: "Sigmar", path: "fonts/playful/Sigmar.woff2" },
  { name: "Spicy Rice", path: "fonts/playful/Spicy_Rice.woff2" },
];
