export const playful = [
  { name: "Atma", url: "/fonts/playful/Atma.woff2" },
  { name: "Chela One", url: "/fonts/playful/Chela_One.woff2" },
  { name: "Chewy", url: "/fonts/playful/Chewy.woff2" },
  { name: "Chicle", url: "/fonts/playful/Chicle.woff2" },
  {
    name: "Covered By Your Grace",
    url: "/fonts/playful/Covered_By_Your_Grace.woff2",
  },
  { name: "Crushed", url: "/fonts/playful/Crushed.woff2" },
  { name: "DynaPuff", url: "/fonts/playful/DynaPuff.woff2" },
  { name: "Gabriela", url: "/fonts/playful/Gabriela.woff2" },
  { name: "Galindo", url: "/fonts/playful/Galindo.woff2" },
  { name: "Gochi Hand", url: "/fonts/playful/Gochi_Hand.woff2" },
  { name: "Jolly Lodger", url: "/fonts/playful/Jolly_Lodger.woff2" },
  { name: "Itim", url: "/fonts/playful/Itim.woff2" },
  { name: "Mouse Memoirs", url: "/fonts/playful/Mouse_Memoirs.woff2" },
  { name: "Patrick Hand", url: "/fonts/playful/Patrick_Hand.woff2" },
  { name: "Ranchers", url: "/fonts/playful/Ranchers.woff2" },
  { name: "Rum Raisin", url: "/fonts/playful/Rum_Raisin.woff2" },
  { name: "Shrikhand", url: "/fonts/playful/Shrikhand.woff2" },
  { name: "Sigmar", url: "/fonts/playful/Sigmar.woff2" },
  { name: "Spicy Rice", url: "/fonts/playful/Spicy_Rice.woff2" },
];
