export const playful = [
  { name: "Atma", path: "lib/fonts/playful/Atma.ttf" },
  { name: "Chela One", path: "lib/fonts/playful/Chela_One.ttf" },
  { name: "Chewy", path: "lib/fonts/playful/Chewy.ttf" },
  { name: "Chicle", path: "lib/fonts/playful/Chicle.ttf" },
  {
    name: "Covered By Your Grace",
    path: "lib/fonts/playful/Covered_By_Your_Grace.ttf",
  },
  { name: "Crushed", path: "lib/fonts/playful/Crushed.ttf" },
  { name: "DynaPuff", path: "lib/fonts/playful/DynaPuff.ttf" },
  { name: "Gabriela", path: "lib/fonts/playful/Gabriela.ttf" },
  { name: "Galindo", path: "lib/fonts/playful/Galindo.ttf" },
  { name: "Gochi Hand", path: "lib/fonts/playful/Gochi_Hand.ttf" },
  { name: "Jolly Lodger", path: "lib/fonts/playful/Jolly_Lodger.ttf" },
  { name: "Itim", path: "lib/fonts/playful/Itim.ttf" },
  { name: "Mouse Memoirs", path: "lib/fonts/playful/Mouse_Memoirs.ttf" },
  { name: "Patrick Hand", path: "lib/fonts/playful/Patrick_Hand.ttf" },
  { name: "Ranchers", path: "lib/fonts/playful/Ranchers.ttf" },
  { name: "Rum Raisin", path: "lib/fonts/playful/Rum_Raisin.ttf" },
  { name: "Shrikhand", path: "lib/fonts/playful/Shrikhand.ttf" },
  { name: "Sigmar", path: "lib/fonts/playful/Sigmar.ttf" },
  { name: "Spicy Rice", path: "lib/fonts/playful/Spicy_Rice.ttf" },
];
